namespace: nrser
name: nansi
version: 0.0.1
readme: README.md
authors:
  - NR$ER (https://github.com/nrser)
description: null
license_file: LICENSE
tags: []
# NOTE: No more dependencies can be added to this list
dependencies:
  community.general: '>=1.3.1'
repository: https://github.com/nrser/nansi
documentation: https://github.com/nrser/nansi
homepage: https://github.com/nrser/nansi
issues: https://github.com/nrser/nansi/issues
#type: flatmap
