- when: nginx_package | test_task_args
  nginx_package: "{{ nginx_package | to_task_args }}"

- when: nginx_dhparam | test_task_args
  nginx_dhparam: "{{ nginx_dhparam | to_task_args }}"
  notify: nginx_restart

# Do the sites before the main config since it can (and by default, does) depend
# on the site configs through including `sites-enabled` and such.
- loop: "{{ nginx_sites }}"
  nginx_site: "{{ item }}"
  notify: nginx_restart

- when: nginx_config | test_task_args
  nginx_config: "{{ nginx_config | to_task_args }}"
  notify: nginx_restart

- when: nginx_service | test_task_args
  nginx_service: "{{ nginx_service | to_task_args }}"
