# Global defaults
nginx_state: present
nginx_config_dir: /etc/nginx
nginx_run_dir: /run
nginx_log_dir: /var/log/nginx
nginx_exe: /usr/sbin/nginx
nginx_config_validate: "{{ nginx_exe }} -t -c %s"
nginx_proxy_websockets: no

nginx_dhparam: yes
nginx_config: yes
nginx_service: yes
nginx_sites: []

# # Firewall
# nginx_firewall_allow: all
# _nginx_ufw_names:
#   http: Nginx HTTP
#   https: Nginx HTTPS
#   all: Nginx Full
#   full: Nginx Full

