- name: Install elixir
  apt:
    # `esl-erlang` packages up all the erlang "apps" as one package... which
    # sound better right now to my rushed, inexperienced-ass.
    # 
    # The "version" are weird as shit...
    # 
    #     1:23.0.3-1
    #     1:23.0.2-2
    #     1:23.0.2-1
    #     1:23.0.1-1
    #     1:23.0-2
    # 
    # You can see them with
    # 
    #     $ apt-cache madison esl-erlang
    # 
    # Yeah, 'cause "madison" is exactly what I think when I want to see
    # available package versions...
    # 
    name: "elixir={{ elixir_version }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
