- when: nginx_site_http
  name: >
    Template HTTP conf for site {{ nginx_site_name }} to
    {{ (nginx_site_available_dir, nginx_site_http_filename) | path | f }}
  template:
    src: http.conf
    dest: "{{ (nginx_site_available_dir, nginx_site_http_filename) | path }}"
    backup: true
  register: _nginx_site_http_conf_result

- when: not nginx_site_http
  with_items:
    - "{{ nginx_site_available_dir }}"
    - "{{ nginx_site_enabled_dir }}"
  name: >
    Remove HTTP conf from {{ item | f }} for site {{ nginx_site_name }}
  file:
    path: "{{ (item, nginx_site_http_filename) | path }}"
    state: absent
  register: _nginx_site_http_conf_result

- when: nginx_site_https
  name: >
    Template HTTPS conf for site {{ nginx_site_name }} to
    {{ (nginx_site_available_dir, nginx_site_https_filename) | path | f }}
  template:
    src: https.conf
    dest: "{{ (nginx_site_available_dir, nginx_site_https_filename) | path }}"
    backup: true
  register: _nginx_site_https_conf_result

- when: not nginx_site_https
  with_items:
    - "{{ nginx_site_available_dir }}"
    - "{{ nginx_site_enabled_dir }}"
  name: >
    Remove HTTPS conf from {{ item | f }} for site {{ nginx_site_name }}
  file:
    path: "{{ (item, nginx_site_https_filename) | path }}"
    state: absent
  register: _nginx_site_http_conf_result

- when: >-
    _nginx_site_http_conf_result.changed or
    _nginx_site_https_conf_result.changed
  name: Validate Nginx config
  command: "{{ nginx_exe }} -t -c {{ nginx_conf_dest | quote }}"
  notify: nginx_restart
