- include_tasks: "{{ (role_path, 'tasks', 'template.yaml') | path }}"

- when: nginx_site_http
  name: >-
    Ensure HTTP config file for {{ nginx_site_name }}
    **IS** linked from {{ nginx_site_enabled_dir | f }}
  file:
    src: "{{ (nginx_site_available_dir, nginx_site_http_filename) | path }}"
    dest: "{{ (nginx_site_enabled_dir, nginx_site_http_filename) | path }}"
    state: link
  register: _nginx_site_http_link_result

- when: nginx_site_https
  name: >-
    Ensure HTTPS config file for {{ nginx_site_name }}
    **IS** linked from {{ nginx_site_enabled_dir | f }}
  file:
    src: "{{ (nginx_site_available_dir, nginx_site_https_filename) | path }}"
    dest: "{{ (nginx_site_enabled_dir, nginx_site_https_filename) | path }}"
    state: link
  register: _nginx_site_https_link_result

- when: >-
    _nginx_site_http_link_result.changed or
    _nginx_site_https_link_result.changed
  name: Validate Nginx config
  command: "{{ nginx_exe }} -t -c {{ nginx_conf_dest | quote }}"
  notify: nginx_restart
  