humans_admin_group: admin
humans_group: humans

humans_admins: "{{ humans | selectattr('admin', 'true') | list }}"
humans_users: "{{ humans | selectattr('admin', 'false') | list }}"

humans_auth_admins_as_users: false
humans_authorized_key_exclusive: "{{ not humans_auth_admins_as_users }}"
