- name: Install the gpg key for packages.erlang-solutions.com/ubuntu
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: Install packages.erlang-solutions.com/ubuntu repo
  apt_repository:
    repo: >-
      deb https://packages.erlang-solutions.com/ubuntu
      {{ ansible_facts.distribution_release }} contrib
    state: present
    update_cache: yes

- name: Install erlang
  apt:
    # `esl-erlang` packages up all the erlang "apps" as one package... which
    # sound better right now to my rushed, inexperienced-ass.
    # 
    # The "version" are weird as shit...
    # 
    #     1:23.0.3-1
    #     1:23.0.2-2
    #     1:23.0.2-1
    #     1:23.0.1-1
    #     1:23.0-2
    # 
    # You can see them with
    # 
    #     $ apt-cache madison esl-erlang
    # 
    # Yeah, 'cause "madison" is exactly what I think when I want to see
    # available package versions...
    # 
    name: "esl-erlang={{ erlang_version }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
